routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]);


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', function () {
        return view('welcome');
    });
        
        
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/companies/dataTables', 'CompanyController@dataTables');
    Route::get('/employees/dataTables', 'EmployeeController@dataTables');
    
    Route::resources([
        'companies' => 'CompanyController',
        'employees' => 'EmployeeController'
    ]);
});
    

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends \Eloquent
{
    protected $table = "company";    
    protected $fillable = [
        'name',
    ];
    public function image()
    {
        return $this->morphOne('App\Image', 'imageable');
    }
    public function employees()
    {
        
        return $this->  hasMany( 'App\Employees' , 'company_id') ;
        
    }
    
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Company;
use App\Image;
use Datatables;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();
        
        return view('companies.index', compact('companies'));
    }
    /**
     * returns json datatables required data.
     */
    
    public function dataTables()
    {
        $model = Company::with('image');
//         return dataTables()->of(Company::query())->make(true);
        return dataTables()->eloquent($model)
        ->addColumn('image', function (Company $company) {
            if(is_object($company->image)){
                return $company->image->image;
            }
            return null;
        })
        ->toJson();
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>    ['required',
                'unique:company',
            ],
            'image'=>'image',
        ]);
        
        $company = new Company([
            'name' => $request->get('name'),
        ]);
        $company->save();
        
        //Save image
        if($request->has('image')){
            $imageName = time().'.'.request()->image->getClientOriginalExtension();
            request()->image->move(public_path('uploads/companies'), $imageName);
            $image = new Image([
                'image' =>  $imageName,
            ]);
            $company->image()->save($image);
        }
        return redirect('/companies')->with('success', 'Company saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add company</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('companies.store') }}" enctype="multipart/form-data" >
          @csrf
          <div class="form-group">    
              <label for="first_name">Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>

          <div class="form-group">
              <label for="last_name">Image:</label>
              <input type="file" class="form-control" name="image" />
          </div>

          <button type="submit" class="btn btn-success btn-primary-outline">Add Company</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
    		<a class='btn btn-success float-right' href='{{ url("companies/create") }}'>Add new company</a>
            <h1 class="display-3">Companies</h1>
          <table class="table table-striped" id="table">
            <thead>
                <tr>
                  <td>ID</td>
                  <td>Name</td>
                  <td>Image</td>
                </tr>
            </thead>
          </table>
          
          
          
          
          
        <div>
    </div>
@endsection


@section('scripts')
    <script>
         $(document).ready( function () {
        	    $('#table').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: '{{ url('companies/dataTables') }}',
                    columns: [
                             { data: 'id', name: 'id' },
                             { data: 'name', name: 'name' },
                             { data: 'image', 
                                 	  name: 'image',
                                 	  "render" : function ( data) {
                                 			if(data != null){
                                 				return '<img class="list-img" src="'+ data +'"/>';
                                 			}
                                 			return '';		                      	     	  
        			               	  } 
			               	  }
                          ],

                      
                 });
        	} );
         
     </script>

@endsection